export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const RESET_CURRENT_QUESTION = 'RESET_CURRENT_QUESTION';
export const INCREMENT_CURRENT_QUESTION = 'INCREMENT_CURRENT_QUESTION';
export const SUBMIT_SCORE = 'SUBMIT_SCORE';
export const RESET_RECENT_SCORE = 'RESET_RECENT_SCORE';
